### PR TITLE
Update to a newer version of alexandria

### PR DESCRIPTION
**Pull request by phyrog**
Updates alexandria to the most recent commit b1c6ee03c41e0db97989ae38e70da4d8263e09d1.

### CODE REVIEW

**Comment by phyrog** [comment]
Note that cram-code/cram_highlevel#47 and cram-code/cram_core#35 still apply to this PR.

**Comment by gaya-** [comment]
So, where did you get the source code from? In this situation having a makefile would really help. Otherwise the source is unclear.

**Comment by phyrog** [comment]
The source is taken directly from the git repo at git://common-lisp.net/projects/alexandria/alexandria.git. What kind of a Makefile do you mean? To update the source?

**Comment by gaya-** [comment]
Something like this:
https://github.com/cram-code/cram_3rdparty/blob/20a026c37313d598f48fb52c7c6a928aa832ccd3/alexandria/Makefile
But now instead of downloading a tarball and unpacking it we'd be ```git clone```-ing and checking out a specific tag. My programmer's gut tells me that this would be cleaner than manually copy-pasting code. There was a discussion on Github or the mailing list about this already but I can't find it. As far as I can remember it comes down to the following pros and cons:

+ You know where exactly the update came from => sense of reliability
+ Next time  you want to update the libs you know where to look
+ You don't have a copy of other people's code in your repo, in fact you only have a makefile

- If the server with the lib repo is down and you only did ```git pull``` or ```wstool update``` and not ```catkin_make``` you're in trouble.
- If you're on a train and wanted to work (without internet) and only did ```git pull``` or ```wstool update``` and not ....

This basically comes down to the same thing as Git submodules. Only you don't have to remember to call an extra Git command because you're going to compile the packages beforehand anyway.

IMHO the pluses outweigh the minuses.

That is:
- It takes some effort to write a clean Makefile.

**Comment by airballking** [comment]
As of catkin_make it is discouraged to download anything during the build process:

"Historically, third party packages have been wrapped in rosbuild packages, using one of the download_and_build Make scripts [1]. This has since been discouraged [2], as it often lead to failures on the build farm and generally is considered bad form for a package."
(taken from here: http://www.ros.org/reps/rep-0136.html)

That is why I have switchted to manually copying the source code of 3rd party packages.

**Comment by gaya-** [comment]
Ok, ledit enough.
@phyrog could you please add a little readme with a link to the source of the library? README.md or something.

**Comment by airballking** [comment]
Sorry for being slow today. It's Monday after all...

This type of information can be stored in the package.xml:
```
<url type="website">http://common-lisp.net/project/alexandria/</url>
<url type="bugtracker">https://github.com/cram-code/cram_core/issues</url>
<url type="repository">https://github.com/cram-code/cram_core</url>
<url type="repository">put original repo url here</url>
```

Unfortunately, there is no slot for an external version. So, you can either put it into the description of the package.xml or add a comment like this:
```<!--external-version>external version here</external-version-->```

**Comment by gaya-** [comment]
version + tag

**Comment by phyrog** [comment]
So, I added the repository tag and put the commit id as the external-version. Would that be enough?

What do you think of the update-solution I proposed over at https://github.com/cram-code/cram_3rdparty/pull/7#issuecomment-81557554? Basically having an extra branch with the libraries included as submodules + a Makefile on that branch to update a specific library and commit the updated files on a feature branch for a PR.
That way you would have the origin of the source code directly at hand without having the problem with bloom and submodules. Plus you have the benefit of easy updating (e.g. make update PKG=alexandria).

**Comment by phyrog** [comment]
Oh, by the way: It seems, all the other roslisp packages have a directory named `asdf` with symlinks to all the .asd files. Is this something that is also wanted for the 3rd party libs?

**Comment by gaya-** [comment]
No, bloom doesn't like symlinks. It's the CRAM packages that aren't released yet that have those.

**Comment by phyrog** [comment]
Oh okay.

**Comment by airballking** [comment]
@phyrog I like the idea of having a script that automatically fetches the newest version of an external library and creates a feature branch with this update. If you feel like providing such a feature I'd be very happy!

That being said, my experiences with git submodules are very limited. So, I am not sure whether using a make-script + git submodules is a good technical solution. Maybe just an update script which clones the latest version of a library into /tmp and copies the files into the correct location is already enough?

**Comment by phyrog** [comment]
@airballking I created a PR for such a script at #10

**Comment by airballking** [comment]
The current version of master is already tagged. So, I suggest merging this single PR and working with it in daily work to see whether stuff breaks. If it does, people can go back with the tag ```0.1.2```.

Sounds fine?

**Comment by airballking** [comment]
```ping ``` for proposition of merging.

**Comment by gaya-** [comment]
I will test this these couple of days and merge it in if nothing breaks.

**Comment by phyrog** [comment]
@gaya- Did you find some time to test this yet?

**Comment by gaya-** [comment]
Yes, I'm waiting for https://github.com/cram-code/cram_core/pull/36 to be merged in, then I'll merge this asap.

**Pull request merged**
