### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by phyrog**
Update all libs to newer versions, since some of them are rather old.

### CODE REVIEW

**Comment by airballking** [comment]
@phyrog thank you for providing this pull request! 

Could you please provide each of the library upgrades as a separate pull request? We would like to make pull requests as concise as possible. Having a separate pull request per lib would make code reviewing and upgrading easier.

**Comment by airballking** [comment]
After some code browsing I saw that you included the external libs as gitsubmodules. This is a change of design that we first need to discuss earlier!

@fairlight1337 @gaya- @moesenle what do you think?

pro:
- upgrading each lib is probably much easier

don't know:
- Does bloom releasing support gitsubmodules?

con:
If the referenced git repositories go offline, we are in trouble.

**Comment by fairlight1337** [comment]
In favor of that as well. Submodules also makes checking out hell more complicated as it gets easy to forget that. Or does catkin check out submodules all by itself?

**Comment by phyrog** [comment]
Alright, I'll create seperate pull requests. But considering the hassle to update the libraries, you might want to think about a way to automate the update process (e.g. have a separate branch with submodules and a script to update them and commit them to the master branch/create PRs).

**Comment by gaya-** [comment]
Wstool supports submodules, so when you use ```wstool update``` it checks out everything.

We used to have make scripts that would download a ```tar``` and unpack it into the ```src``` directory. If you can be bothered, you could write a make script that checks out a specific tag of the git repo if it wasn't checked out already. Then at least the URLs of the libraries are stored somewhere for future reference. You could probably look back in the history of ```cram_3rdparty``` and see how it was done. Not quite sure if we kept the history for this repo though.

**Comment by gaya-** [comment]
Also, just in case this might be useful, you can ```git reset --soft HEAD^``` to get all the changes back into the repo while discarding the last commit. Then you can ```git add ...``` each directory separately and create a commit and branch and whatever for it.

**Pull request closed without merging**
