### PR TITLE
Include 3rd party code as submodules

### PR DESCRIPTION
**Pull request by phyrog**
Basically removes (almost) all code from this repository and includes it as submodules. The only library left in this repo is synchronization-tools, since the original code seems to reside in a darcs repo.

This will make updating these libraries a lot easier. Was there a reason not to do this in the first place?

Note: Since the versions of the libraries might be different from the previous version, this should be thoroughly tested before merging. Also, with the newer alexandria version, there seems to be a naming conflict with cram_utilities (the extremum function), which should be shadowed before merging.

### CODE REVIEW

**Comment by phyrog** [comment]
I created a pull request (cram-code/cram_core#35) on cram_core to remove the conflict with the newer alexandria version.

**Comment by gaya-** [comment]
Unfortunately, bloom doesn't support Git submodules at the moment. If we want to continue releasing cram-core this PR will have to wait until the feature is implemented in bloom.

**Comment by phyrog** [comment]
Oh well, I guess this will have to wait then. But the libraries should be updated nevertheless.

**Comment by phyrog** [comment]
I created a new pull request #7  for updated libs without submodules, so I'm closing this one for now.

**Pull request closed without merging**
