### PR TITLE
Update to a newer version of babel

### PR DESCRIPTION
**Pull request by phyrog**
Updates to the newest git version of babel. See package.xml for more info on the exact version and the origin repository.

### CODE REVIEW

**Comment by phyrog** [comment]
So, any chance of getting these PRs merged some day? I'll close them otherwise.

**Comment by gaya-** [comment]
There is a chance :) Why do you want to close them? They're on a separate branch in your repository, do they distract you?

**Comment by phyrog** [comment]
Well they clutter my PR overview to a point where I really have to look if a PR is an active (as in: things are moving forward) one or not. Also, having 14 PRs open in this repository alone without any reaction for 3 months does not really contribute to motivate me to submit further PRs.

**Comment by gaya-** [comment]
@phyrog I'm going to test the upgraded libraries all at once, is there any difference between the updated_libs branch and all the other single branches codewise? I don't have time and motivation to test each lib separately, unfortunately.

Btw, you can always close PRs if they really annoy you. You can even remove your fork of the repo. In both cases the PR will still be available to be used, it might just take a bit more manual work from the maintainers to merge it in.

**Comment by gaya-** [comment]
Never mind, there seems to be a problem with synchronization_tools in the unpdated_libs branch anyway. I'll do them separately.

**Pull request closed without merging**
